### ISSUE TITLE
Add License headers for all files

### ISSUE THREAD

**Issue by karlcow** [mozilla/trexa-service#11]
Related to #5

There's a general license declaration in the repo. 
I don't know if there is a policy from Mozilla that the license should be in each individual file.

**Comment by miketaylr** [comment]
I didn't know either, but just learned something from https://www.mozilla.org/en-US/MPL/2.0/FAQ/

> **Q22: Does MPL 2.0 require that the MPL 2.0 license notice header be included in every file?**
> The license notice must be in some way "attached" to each file. (Sec. 1.4.) In cases where putting it in the file is impossible or impractical, that requirement can be fulfilled by putting the notice somewhere that a recipient "would be likely to look for such a notice," such as a LICENSE file in the same directory as the file. (Ex. A.) The license notice is as short as possible (3 lines) to make it easy to put in as many different types of files as possible.
> 
> While the license permits putting the header somewhere other than the file itself, individual files often end up being distributed on their own, without the rest of the software they were authored with. As a result, putting the license notice in the file is the surest way to ensure that recipients are always notified.
> 
> For your convenience, Mozilla has produced boilerplate headers formatted with several common > 'comment' syntaxes, suitable for copying and pasting.

So technically the current approach is fine, but I think it's not a bad idea to add the header to individual files since they may end up being used or distributed individually.
