### ISSUE TITLE
first n lines of a file with StopIteration

### ISSUE THREAD

**Issue by karlcow** [mozilla/trexa-service#14]
https://github.com/mozilla/trexa-service/blob/1105042293e5424dfe97bb9e7f8ce1e96261e9db/trexa/helpers.py#L57-L58

This is a fast elegant solution.
Just a warning that if the number is actually bigger than the number of lines. There will be a StopIteration error and the `head` will be empty.

You could use `islice` too it will not fail on a number bigger. 
It has a reputation to be slower, but on a very small file I didn't find differences.

```bash
python -m timeit 'with open("blah.txt", "r") as f:''    head = [next(f) for x in range(3)]'
5000 loops, best of 5: 89.2 usec per loop

python -m timeit 'from itertools import islice;' 'with open("blah.txt", "r") as f:' '    head = list(islice(f,3))'
5000 loops, best of 5: 90.5 usec per loop
```

**Comment by miketaylr** [comment]
Thanks, good recommendation. I don't think we need to be too worried about performance. The single consumer of the service is the TSCI which takes a few hours to run anyways (once a week, via cron).
