### ISSUE TITLE
Tools directory for things unrelated to the app. 

### ISSUE THREAD

**Issue by karlcow** [mozilla/trexa-service#15]
Related to #5 

Reading `get_tranco` I realized a couple of inconsistencies.

https://github.com/mozilla/trexa-service/blob/1105042293e5424dfe97bb9e7f8ce1e96261e9db/trexa/helpers.py#L63-L87

`TRANCO_100K_URI` is hardcoded in the module while `CSV_DOWNLOADS_DEST` is in the config
That seems inconsistent.

Why not passing the config object in build_list.
https://github.com/mozilla/trexa-service/blob/1105042293e5424dfe97bb9e7f8ce1e96261e9db/build_list.py#L19-L22

`build_list` is not connected to the app at all, but for it to function, helpers needs to import the full `app` to just get access to the config object.

`from trexa import app`

Probably not very useful. It would be better to import the config object just for the tools.

Suggestion:
Create a tools directory which separate the helpers from the app and the tools.

**Comment by karlcow** [comment]
Also on the nit side: in the helper file. Sometimes the code uses single quotes sometimes double quotes.
The equivalent of [prettier for python is black](https://black.readthedocs.io/en/stable/).

**Comment by karlcow** [comment]
https://github.com/mozilla/trexa-service/blob/1105042293e5424dfe97bb9e7f8ce1e96261e9db/trexa/helpers.py#L90-L97

I would rewrite this with the csv module.


```python
import csv

tld_list = []
with open('foo.csv', newline='') as csvfile:
    csvdata = csv.reader(csvfile, delimiter=',')
    for row in csvdata:
        # strip only if there's a fear for spaces in the file. if not you can drop it and make the function evern shorter.
        tld = row[1].strip()
        tld_list.append(tld)
```

**Comment by karlcow** [comment]
Same thing for the writer, instead of formatting the line, the code can use the csv module.

https://github.com/mozilla/trexa-service/blob/1105042293e5424dfe97bb9e7f8ce1e96261e9db/trexa/helpers.py#L100-L107

**Comment by karlcow** [comment]
```diff
-    a = a[0:list_size]
+    a = a[:list_size]
```

🙈 
https://github.com/mozilla/trexa-service/blob/1105042293e5424dfe97bb9e7f8ce1e96261e9db/trexa/helpers.py#L123-L128

```python
>>> list_size = 3
>>> a =[1, 2, 3, 4, 5, 6]
>>> a[:list_size]
[1, 2, 3]
>>> a = a[:list_size]
>>> alexa_subset_length = len(a)
>>> alexa_subset_length
3
```

`assert alexa_subset == list_size` (always `True` nope?)

So why not doing:

```python
    # Open and parse the ALEXA TLD list from local csv.
    a = read_list_csv(alexa_list)
    # Truncate ALEXA list to minimum necessary elements to process.
    a = a[0:list_size]
    # Save the ALEXA list into a set type for sanity checking list
    # combination operations.
    alexa_set = set(a)
```

and use `list_size` directly later on as it is exactly the same thing. Or maybe I missed something.


Any reasons to mix the `f''` string with `format()` style?

```python
>>> 'foobar {0}'.format(1)
'foobar 1'
```

so this seems a bit heavy.

```python
>>> 'foobar {0}'.format(str(1))
'foobar 1'
```


https://github.com/mozilla/trexa-service/blob/1105042293e5424dfe97bb9e7f8ce1e96261e9db/trexa/helpers.py#L187-L191

🚨 
[`csv`](https://docs.python.org/3/library/csv.html) is a module name, possible conflicts.
[`zip`](https://docs.python.org/3/library/functions.html#zip) is a function name, possible conflicts.

**Comment by karlcow** [comment]
Also if necessary 
https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

**Comment by miketaylr** [comment]
Thanks, good suggestions here. A lot of the code in helpers is just a straight port (aka copy+paste from the initial trexa merge code. Lots to improve. :)
