### ISSUE TITLE
Use tranco package to build custom date lists

### ISSUE THREAD

**Issue by birdsarah** [mozilla/trexa-service#2]
https://pypi.org/project/tranco/

**Comment by miketaylr** [comment]
Oh cool, didn't know that existed. :D

**Comment by miketaylr** [comment]
@birdsarah just to clarify, is this issue about adding new functionality or merely porting the existing code that downloads tranco lists ("by hand")?

**Comment by birdsarah** [comment]
Great question. You can choose :) 
I just thought it was useful, and it would mean you can backfill if the service went down as I couldn’t find a way to generate a url for a list for a particular date.a
