### ISSUE TITLE
README Installation Instructions 

### ISSUE THREAD

**Issue by karlcow** [mozilla/trexa-service#7]
Related to #5

https://github.com/mozilla/trexa-service/blob/master/README.md
 
There's a missing step:

1. clone the repo

(here `cd trexa-service` )

2. run `python3 -m venv env`
3. run `source env/bin/activate`
4. run `pip3 install -r requirements.txt`

**Comment by miketaylr** [comment]
This was fixed in https://github.com/mozilla/trexa-service/pull/8
